# -*- coding: utf-8 -*-
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Settings (QtGui.QWidget):
    def __init__(self,settingsList = []):
        QtGui.QWidget.__init__(self)
        self.initUi()
        self.defaultList = [50,-50,100,-100,-100,-80,-80,100,100,80,
                            80,50,30,20,50,50,50,50,50,50,50,
                            50,50,30,10,-50,-50,-30,15,10,5,
                            -15,-10,-5]
        if settingsList:
            self.loadVal(settingsList)
            #self.defaultValues)
    def getVal(self):
        li = []
        li.append(self.positiveSignalSpinBox.value())
        li.append(self.negativeSignalSpinBox.value())
        li.append(self.trendSpinBox.value())
        li.append(self.headAndShouldersSpinBox.value())
        li.append(self.tripleTopSpinBox.value())
        li.append(self.risingWedgeSpinBox.value())
        li.append(self.fallingTriangleSpinBox.value())
        li.append(self.reversedHeadAndShouldersSpinBox.value())
        li.append(self.tripleBottomSpinBox.value())
        li.append(self.fallingWedgeSpinBox.value())
        li.append(self.risingTriangleSpinBox.value())
        li.append(self.symetricTriangleSpinBox.value())
        li.append(self.rectangleSpinBox.value())
        li.append(self.flagPennantSpinBox.value())
        li.append(self.oscilatorsSpinBox.value())
        li.append(self.newHighNewLowSpinBox.value())
        li.append(self.bollingerSpinBox.value())
        li.append(self.momentumSpinBox.value())
        li.append(self.rocSpinBox.value())
        li.append(self.cciSpinBox.value())
        li.append(self.rsiSpinBox.value())
        li.append(self.williamsSpinBox.value())
        li.append(self.risingBreakawayGapSpinBox.value())
        li.append(self.risingContinuationGapSpinBox.value())
        li.append(self.fallingExhaustionGapSpinBox.value())
        li.append(self.fallingBreakawayGapSpinBox.value())
        li.append(self.risingExhaustionGapSpinBox.value())
        li.append(self.fallingContinuationGapSpinBox.value())
        li.append(self.bull3SpinBox.value())
        li.append(self.morningStarSpinBox.value())
        li.append(self.bear3SpinBox.value())
        li.append(self.piercingSpinBox.value())
        li.append(self.eveningStarSpinBox.value())
        li.append(self.darkCloudSpinBox.value())

        li2 = [] # styl lini
        li2.append(0)
        li2.append(0)
        li2.append(self.trendLineStyle.currentIndex())
        li2.append(self.headAndShouldersLineStyle.currentIndex())
        li2.append(self.tripleTopLineStyle.currentIndex())
        li2.append(self.risingWedgeLineStyle.currentIndex())
        li2.append(self.fallingTriangleLineStyle.currentIndex())
        li2.append(self.reversedHeadAndShouldersLineStyle.currentIndex())
        li2.append(self.tripleBottomLineStyle.currentIndex())
        li2.append(self.fallingWedgeLineStyle.currentIndex())
        li2.append(self.risingTriangleLineStyle.currentIndex())
        li2.append(self.symetricTriangleLineStyle.currentIndex())
        li2.append(self.rectangleLineStyle.currentIndex())
        li2.append(self.flagPennantLineStyle.currentIndex())
        li2.append(self.oscilatorsLineStyle.currentIndex())
        li2.append(self.newHighNewLowLineStyle.currentIndex())
        li2.append(self.bollingerLineStyle.currentIndex())
        li2.append(self.momentumLineStyle.currentIndex())
        li2.append(self.rocLineStyle.currentIndex())
        li2.append(self.cciLineStyle.currentIndex())
        li2.append(self.rsiLineStyle.currentIndex())
        li2.append(self.williamsLineStyle.currentIndex())
        li2.append(self.risingBreakawayGapLineStyle.currentIndex())
        li2.append(self.risingContinuationGapLineStyle.currentIndex())
        li2.append(self.fallingExhaustionGapLineStyle.currentIndex())
        li2.append(self.fallingBreakawayGapLineStyle.currentIndex())
        li2.append(self.risingExhaustionGapLineStyle.currentIndex())
        li2.append(self.fallingContinuationGapLineStyle.currentIndex())
        li2.append(self.bull3LineStyle.currentIndex())
        li2.append(self.morningStarLineStyle.currentIndex())
        li2.append(self.bear3LineStyle.currentIndex())
        li2.append(self.piercingLineStyle.currentIndex())
        li2.append(self.eveningStarLineStyle.currentIndex())
        li2.append(self.darkCloudLineStyle.currentIndex())

        #Kolor
        li3 = []
        li3.append(0)
        li3.append(0)
        li3.append(self.trendColor.currentIndex())
        li3.append(self.headAndShouldersColor.currentIndex())
        li3.append(self.tripleTopColor.currentIndex())
        li3.append(self.risingWedgeColor.currentIndex())
        li3.append(self.fallingTriangleColor.currentIndex())
        li3.append(self.reversedHeadAndShouldersColor.currentIndex())
        li3.append(self.tripleBottomColor.currentIndex())
        li3.append(self.fallingWedgeColor.currentIndex())
        li3.append(self.risingTriangleColor.currentIndex())
        li3.append(self.symetricTriangleColor.currentIndex())
        li3.append(self.rectangleColor.currentIndex())
        li3.append(self.flagPennantColor.currentIndex())
        li3.append(self.oscilatorsColor.currentIndex())
        li3.append(self.newHighNewLowColor.currentIndex())
        li3.append(self.bollingerColor.currentIndex())
        li3.append(self.momentumColor.currentIndex())
        li3.append(self.rocColor.currentIndex())
        li3.append(self.cciColor.currentIndex())
        li3.append(self.rsiColor.currentIndex())
        li3.append(self.williamsColor.currentIndex())
        li3.append(self.risingBreakawayGapColor.currentIndex())
        li3.append(self.risingContinuationGapColor.currentIndex())
        li3.append(self.fallingExhaustionGapColor.currentIndex())
        li3.append(self.fallingBreakawayGapColor.currentIndex())
        li3.append(self.risingExhaustionGapColor.currentIndex())
        li3.append(self.fallingContinuationGapColor.currentIndex())
        li3.append(self.bull3Color.currentIndex())
        li3.append(self.morningStarColor.currentIndex())
        li3.append(self.bear3Color.currentIndex())
        li3.append(self.piercingColor.currentIndex())
        li3.append(self.eveningStarColor.currentIndex())
        li3.append(self.darkCloudColor.currentIndex())

        #check box
        li4 = []
        li4.append(False)
        li4.append(False)
        li4.append(self.trendCheckBox.isChecked())
        li4.append(self.headAndShouldersCheckBox.isChecked())
        li4.append(self.tripleTopCheckBox.isChecked())
        li4.append(self.risingWedgeCheckBox.isChecked())
        li4.append(self.fallingTriangleCheckBox.isChecked())
        li4.append(self.reversedHeadAndShouldersCheckBox.isChecked())
        li4.append(self.tripleBottomCheckBox.isChecked())
        li4.append(self.fallingWedgeCheckBox.isChecked())
        li4.append(self.risingTriangleCheckBox.isChecked())
        li4.append(self.symetricTriangleCheckBox.isChecked())
        li4.append(self.rectangleCheckBox.isChecked())
        li4.append(self.flagPennantCheckBox.isChecked())
        li4.append(self.oscilatorsCheckBox.isChecked())
        li4.append(self.newHighNewLowCheckBox.isChecked())
        li4.append(self.bollingerCheckBox.isChecked())
        li4.append(self.momentumCheckBox.isChecked())
        li4.append(self.rocCheckBox.isChecked())
        li4.append(self.cciCheckBox.isChecked())
        li4.append(self.rsiCheckBox.isChecked())
        li4.append(self.williamsCheckBox.isChecked())
        li4.append(self.risingBreakawayGapCheckBox.isChecked())
        li4.append(self.risingContinuationGapCheckBox.isChecked())
        li4.append(self.fallingExhaustionGapCheckBox.isChecked())
        li4.append(self.fallingBreakawayGapCheckBox.isChecked())
        li4.append(self.risingExhaustionGapCheckBox.isChecked())
        li4.append(self.fallingContinuationGapCheckBox.isChecked())
        li4.append(self.bull3CheckBox.isChecked())
        li4.append(self.morningStarCheckBox.isChecked())
        li4.append(self.bear3CheckBox.isChecked())
        li4.append(self.piercingCheckBox.isChecked())
        li4.append(self.eveningStarCheckBox.isChecked())
        li4.append(self.darkCloudCheckBox.isChecked())
        return [li,li2,li3,li4]
        
        
    def loadVal(self,lis = []):
        if not lis:
            li = self.defaultList
            li2 =[0 for i in range(34)]
            li3 = [0 for i in range(34)]
            li4 = [True for i in range(34)]
        else:
            li = lis[0]
            li2 = lis[1]
            li3 = lis[2]
            li4 = lis[3]
        self.positiveSignalSpinBox.setValue(li[0])
        self.negativeSignalSpinBox.setValue(li[1])
        self.trendSpinBox.setValue( li[2])

        self.trendLineStyle.setCurrentIndex(li2[2])

        self.trendColor.setCurrentIndex(li3[2])

        self.trendCheckBox.setChecked(li4[2])      

        """Formacje"""
        #Odwrocenie trendu wzrostowego
        self.headAndShouldersSpinBox.setValue(li[3])
        self.tripleTopSpinBox.setValue(li[4])
        self.risingWedgeSpinBox.setValue(li[5])
        self.fallingTriangleSpinBox.setValue(li[6])
        
        self.headAndShouldersLineStyle.setCurrentIndex(li2[3])
        self.tripleTopLineStyle.setCurrentIndex(li2[4])
        self.risingWedgeLineStyle.setCurrentIndex(li2[5])
        self.fallingTriangleLineStyle.setCurrentIndex(li2[6])
        
        self.headAndShouldersColor.setCurrentIndex(li3[3])
        self.tripleTopColor.setCurrentIndex(li3[4])
        self.risingWedgeColor.setCurrentIndex(li3[5])
        self.fallingTriangleColor.setCurrentIndex(li3[6])

        self.headAndShouldersCheckBox.setChecked(li4[3])
        self.tripleTopCheckBox.setChecked(li4[4])
        self.risingWedgeCheckBox.setChecked(li4[5])
        self.fallingTriangleCheckBox.setChecked(li4[6])

        #Odwrocenie trendu spadkowego
        self.reversedHeadAndShouldersSpinBox.setValue(li[7])
        self.tripleBottomSpinBox.setValue(li[8])
        self.fallingWedgeSpinBox.setValue(li[9])
        self.risingTriangleSpinBox.setValue(li[10])
        
        self.reversedHeadAndShouldersLineStyle.setCurrentIndex(li2[7])
        self.tripleBottomLineStyle.setCurrentIndex(li2[8])
        self.fallingWedgeLineStyle.setCurrentIndex(li2[9])
        self.risingTriangleLineStyle.setCurrentIndex(li2[10])
        
        self.reversedHeadAndShouldersColor.setCurrentIndex(li3[7])
        self.tripleBottomColor.setCurrentIndex(li3[8])
        self.fallingWedgeColor.setCurrentIndex(li3[9])
        self.risingTriangleColor.setCurrentIndex(li3[10])

        self.reversedHeadAndShouldersCheckBox.setChecked(li4[7])
        self.tripleBottomCheckBox.setChecked(li4[8])
        self.fallingWedgeCheckBox.setChecked(li4[9])
        self.risingTriangleCheckBox.setChecked(li4[10])

        #Kontynuacja trendu
        self.symetricTriangleSpinBox.setValue(li[11])
        self.rectangleSpinBox.setValue(li[12])
        self.flagPennantSpinBox.setValue(li[13])
        
        self.symetricTriangleLineStyle.setCurrentIndex(li2[11])
        self.rectangleLineStyle.setCurrentIndex(li2[12])
        self.flagPennantLineStyle.setCurrentIndex(li2[13])
        
        self.symetricTriangleColor.setCurrentIndex(li3[11])
        self.rectangleColor.setCurrentIndex(li3[12])
        self.flagPennantColor.setCurrentIndex(li3[13])

        self.symetricTriangleCheckBox.setChecked(li4[11])
        self.rectangleCheckBox.setChecked(li4[12])
        self.flagPennantCheckBox.setChecked(li4[13])

        """Wskazniki i oscylatory"""
        self.oscilatorsSpinBox.setValue(li[14])
        self.newHighNewLowSpinBox.setValue(li[15])
        self.bollingerSpinBox.setValue(li[16])
        self.momentumSpinBox.setValue(li[17])
        self.rocSpinBox.setValue(li[18])
        self.cciSpinBox.setValue(li[19])
        self.rsiSpinBox.setValue(li[20])
        self.williamsSpinBox.setValue(li[21])
        
        self.oscilatorsLineStyle.setCurrentIndex(li2[14])
        self.newHighNewLowLineStyle.setCurrentIndex(li2[15])
        self.bollingerLineStyle.setCurrentIndex(li2[16])
        self.momentumLineStyle.setCurrentIndex(li2[17])
        self.rocLineStyle.setCurrentIndex(li2[18])
        self.cciLineStyle.setCurrentIndex(li2[19])
        self.rsiLineStyle.setCurrentIndex(li2[20])
        self.williamsLineStyle.setCurrentIndex(li2[21])
        
        self.oscilatorsColor.setCurrentIndex(li3[14])
        self.newHighNewLowColor.setCurrentIndex(li3[15])
        self.bollingerColor.setCurrentIndex(li3[16])
        self.momentumColor.setCurrentIndex(li3[17])
        self.rocColor.setCurrentIndex(li3[18])
        self.cciColor.setCurrentIndex(li3[19])
        self.rsiColor.setCurrentIndex(li3[20])
        self.williamsColor.setCurrentIndex(li3[21])

        self.oscilatorsCheckBox.setChecked(li4[14])
        self.newHighNewLowCheckBox.setChecked(li4[15])
        self.bollingerCheckBox.setChecked(li4[16])
        self.momentumCheckBox.setChecked(li4[17])
        self.rocCheckBox.setChecked(li4[18])
        self.cciCheckBox.setChecked(li4[19])
        self.rsiCheckBox.setChecked(li4[20])
        self.williamsCheckBox.setChecked(li4[21])

        """Luki"""
        #Wzrostowe
        self.risingBreakawayGapSpinBox.setValue(li[22])
        self.risingContinuationGapSpinBox.setValue(li[23])
        self.fallingExhaustionGapSpinBox.setValue(li[24])
        
        self.risingBreakawayGapLineStyle.setCurrentIndex(li2[22])
        self.risingContinuationGapLineStyle.setCurrentIndex(li2[23])
        self.fallingExhaustionGapLineStyle.setCurrentIndex(li2[24])
        
        self.risingBreakawayGapColor.setCurrentIndex(li3[22])
        self.risingContinuationGapColor.setCurrentIndex(li3[23])
        self.fallingExhaustionGapColor.setCurrentIndex(li3[24])

        self.risingBreakawayGapCheckBox.setChecked(li4[22])
        self.risingContinuationGapCheckBox.setChecked(li4[23])
        self.fallingExhaustionGapCheckBox.setChecked(li4[24])
        
        #Spadkowe
        self.fallingBreakawayGapSpinBox.setValue(li[25])
        self.risingExhaustionGapSpinBox.setValue(li[26])
        self.fallingContinuationGapSpinBox.setValue(li[27])
        
        self.fallingBreakawayGapLineStyle.setCurrentIndex(li2[25])
        self.risingExhaustionGapLineStyle.setCurrentIndex(li2[26])
        self.fallingContinuationGapLineStyle.setCurrentIndex(li2[27])
        
        self.fallingBreakawayGapColor.setCurrentIndex(li3[25])
        self.risingExhaustionGapColor.setCurrentIndex(li3[26])
        self.fallingContinuationGapColor.setCurrentIndex(li3[27])

        self.fallingBreakawayGapCheckBox.setChecked(li4[25])
        self.risingExhaustionGapCheckBox.setChecked(li4[26])
        self.fallingContinuationGapCheckBox.setChecked(li4[27])

        """Formacje swiecowe"""
        #sygnal kupna
        self.bull3SpinBox.setValue(li[28])
        self.morningStarSpinBox.setValue(li[29])
        self.piercingSpinBox.setValue(li[30])
        
        self.bull3LineStyle.setCurrentIndex(li2[28])
        self.morningStarLineStyle.setCurrentIndex(li2[29])
        self.piercingLineStyle.setCurrentIndex(li2[30])
        
        self.bull3Color.setCurrentIndex(li3[28])
        self.morningStarColor.setCurrentIndex(li3[29])
        self.piercingColor.setCurrentIndex(li3[30])

        self.bull3CheckBox.setChecked(li4[28])
        self.morningStarCheckBox.setChecked(li4[29])
        self.piercingCheckBox.setChecked(li4[30])

        #sygnal sprzedazy
        self.bear3SpinBox.setValue(li[31])
        self.eveningStarSpinBox.setValue(li[32])
        self.darkCloudSpinBox.setValue(li[33])
        
        self.bear3LineStyle.setCurrentIndex(li2[31])
        self.eveningStarLineStyle.setCurrentIndex(li2[32])
        self.darkCloudLineStyle.setCurrentIndex(li2[33])
        
        self.bear3Color.setCurrentIndex(li3[31])
        self.eveningStarColor.setCurrentIndex(li3[32])
        self.darkCloudColor.setCurrentIndex(li3[33])

        self.bear3CheckBox.setChecked(li4[31])
        self.eveningStarCheckBox.setChecked(li4[32])
        self.darkCloudCheckBox.setChecked(li4[33])

    def initUi(self):
        #self.setMaximumSize(QtCore.QSize(1200, 750))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(self)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.trendLineStyle = LineStyleComboBox()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trendLineStyle.sizePolicy().hasHeightForWidth())
        self.trendLineStyle.setSizePolicy(sizePolicy)
        self.trendLineStyle.setObjectName(_fromUtf8("trendLineStyle"))
        self.gridLayout.addWidget(self.trendLineStyle, 2, 3, 1, 1)
        self.bull3LineStyle = LineStyleComboBox()
        self.bull3LineStyle.setObjectName(_fromUtf8("bull3LineStyle"))
        self.gridLayout.addWidget(self.bull3LineStyle, 2, 15, 1, 1)
        self.label_45 = QtGui.QLabel(self)
        self.label_45.setIndent(15)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout.addWidget(self.label_45, 21, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        self.tripleTopColor = ColorComboBox()
        self.tripleTopColor.setObjectName(_fromUtf8("tripleTopColor"))
        self.gridLayout.addWidget(self.tripleTopColor, 9, 4, 1, 1)
        self.label = QtGui.QLabel(self)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label.setIndent(0)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 5, 1, 1, 4)
        self.trendColor = ColorComboBox()
        self.trendColor.setObjectName(_fromUtf8("trendColor"))
        self.gridLayout.addWidget(self.trendColor, 2, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self)
        self.label_9.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_9.setIndent(0)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 13, 1, 1, 4)
        self.oscilatorsLineStyle = LineStyleComboBox()
        self.oscilatorsLineStyle.setObjectName(_fromUtf8("oscilatorsLineStyle"))
        self.gridLayout.addWidget(self.oscilatorsLineStyle, 1, 9, 1, 1)
        self.label_18 = QtGui.QLabel(self)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 2, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 11, 5, 1, 4)
        self.risingTriangleCheckBox = QtGui.QCheckBox(self)
        self.risingTriangleCheckBox.setText(_fromUtf8(""))
        self.risingTriangleCheckBox.setObjectName(_fromUtf8("risingTriangleCheckBox"))
        self.gridLayout.addWidget(self.risingTriangleCheckBox, 17, 0, 1, 1)
        self.fallingTriangleCheckBox = QtGui.QCheckBox(self)
        self.fallingTriangleCheckBox.setText(_fromUtf8(""))
        self.fallingTriangleCheckBox.setObjectName(_fromUtf8("fallingTriangleCheckBox"))
        self.gridLayout.addWidget(self.fallingTriangleCheckBox, 12, 0, 1, 1)
        self.trendCheckBox = QtGui.QCheckBox(self)
        self.trendCheckBox.setText(_fromUtf8(""))
        self.trendCheckBox.setObjectName(_fromUtf8("trendCheckBox"))
        self.gridLayout.addWidget(self.trendCheckBox, 2, 0, 1, 1)
        self.continuationOfTrendCheckBox = QtGui.QCheckBox(self)
        self.continuationOfTrendCheckBox.setText(_fromUtf8(""))
        self.continuationOfTrendCheckBox.setObjectName(_fromUtf8("continuationOfTrendCheckBox"))
        self.gridLayout.addWidget(self.continuationOfTrendCheckBox, 18, 0, 1, 1)
        self.oscilatorsCheckBox = QtGui.QCheckBox(self)
        self.oscilatorsCheckBox.setText(_fromUtf8(""))
        self.oscilatorsCheckBox.setObjectName(_fromUtf8("oscilatorsCheckBox"))
        self.gridLayout.addWidget(self.oscilatorsCheckBox, 1, 6, 1, 1)
        self.line_4 = QtGui.QFrame(self)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 0, 11, 1, 1)
        self.label_36 = QtGui.QLabel(self)
        self.label_36.setIndent(15)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 16, 7, 1, 1)
        self.cciSpinBox = QtGui.QSpinBox(self)
        self.cciSpinBox.setMaximum(100)
        self.cciSpinBox.setSingleStep(5)
        self.cciSpinBox.setProperty("value", 50)
        self.cciSpinBox.setObjectName(_fromUtf8("cciSpinBox"))
        self.gridLayout.addWidget(self.cciSpinBox, 6, 8, 1, 1)
        self.label_35 = QtGui.QLabel(self)
        self.label_35.setIndent(15)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 15, 7, 1, 1)
        self.fallingExhaustionGapSpinBox = QtGui.QSpinBox(self)
        self.fallingExhaustionGapSpinBox.setMaximum(100)
        self.fallingExhaustionGapSpinBox.setSingleStep(5)
        self.fallingExhaustionGapSpinBox.setProperty("value", 10)
        self.fallingExhaustionGapSpinBox.setObjectName(_fromUtf8("fallingExhaustionGapSpinBox"))
        self.gridLayout.addWidget(self.fallingExhaustionGapSpinBox, 16, 8, 1, 1)
        self.risingContinuationGapSpinBox = QtGui.QSpinBox(self)
        self.risingContinuationGapSpinBox.setMaximum(100)
        self.risingContinuationGapSpinBox.setSingleStep(5)
        self.risingContinuationGapSpinBox.setProperty("value", 30)
        self.risingContinuationGapSpinBox.setObjectName(_fromUtf8("risingContinuationGapSpinBox"))
        self.gridLayout.addWidget(self.risingContinuationGapSpinBox, 15, 8, 1, 1)
        self.negativeSignalSpinBox = QtGui.QSpinBox(self)
        self.negativeSignalSpinBox.setMinimum(-100)
        self.negativeSignalSpinBox.setMaximum(0)
        self.negativeSignalSpinBox.setSingleStep(5)
        self.negativeSignalSpinBox.setProperty("value", -50)
        self.negativeSignalSpinBox.setObjectName(_fromUtf8("negativeSignalSpinBox"))
        self.gridLayout.addWidget(self.negativeSignalSpinBox, 1, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self)
        self.label_23.setIndent(0)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 4, 7, 1, 1)
        self.newHighNewLowSpinBox = QtGui.QSpinBox(self)
        self.newHighNewLowSpinBox.setMaximum(100)
        self.newHighNewLowSpinBox.setSingleStep(5)
        self.newHighNewLowSpinBox.setProperty("value", 50)
        self.newHighNewLowSpinBox.setObjectName(_fromUtf8("newHighNewLowSpinBox"))
        self.gridLayout.addWidget(self.newHighNewLowSpinBox, 2, 8, 1, 1)
        self.label_15 = QtGui.QLabel(self)
        self.label_15.setIndent(15)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 19, 1, 1, 1)
        self.reversalOfRisingTrendCheckBox = QtGui.QCheckBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reversalOfRisingTrendCheckBox.sizePolicy().hasHeightForWidth())
        self.reversalOfRisingTrendCheckBox.setSizePolicy(sizePolicy)
        self.reversalOfRisingTrendCheckBox.setText(_fromUtf8(""))
        self.reversalOfRisingTrendCheckBox.setObjectName(_fromUtf8("reversalOfRisingTrendCheckBox"))
        self.gridLayout.addWidget(self.reversalOfRisingTrendCheckBox, 5, 0, 1, 1)
        self.bull3SpinBox = QtGui.QSpinBox(self)
        self.bull3SpinBox.setMaximum(100)
        self.bull3SpinBox.setSingleStep(5)
        self.bull3SpinBox.setProperty("value", 15)
        self.bull3SpinBox.setObjectName(_fromUtf8("bull3SpinBox"))
        self.gridLayout.addWidget(self.bull3SpinBox, 2, 14, 1, 1)
        self.label_31 = QtGui.QLabel(self)
        self.label_31.setIndent(15)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 4, 13, 1, 1)
        self.bear3SpinBox = QtGui.QSpinBox(self)
        self.bear3SpinBox.setMinimum(-100)
        self.bear3SpinBox.setMaximum(0)
        self.bear3SpinBox.setSingleStep(5)
        self.bear3SpinBox.setProperty("value", -15)
        self.bear3SpinBox.setObjectName(_fromUtf8("bear3SpinBox"))
        self.gridLayout.addWidget(self.bear3SpinBox, 6, 14, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        #self.gridLayout.addItem(spacerItem, 21, 1, 1, 14)
        self.label_22 = QtGui.QLabel(self)
        self.label_22.setIndent(0)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 3, 7, 1, 1)
        self.label_29 = QtGui.QLabel(self)
        self.label_29.setIndent(15)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 2, 13, 1, 1)
        self.oscilatorsSpinBox = QtGui.QSpinBox(self)
        self.oscilatorsSpinBox.setMaximum(100)
        self.oscilatorsSpinBox.setSingleStep(5)
        self.oscilatorsSpinBox.setProperty("value", 50)
        self.oscilatorsSpinBox.setObjectName(_fromUtf8("oscilatorsSpinBox"))
        self.gridLayout.addWidget(self.oscilatorsSpinBox, 1, 8, 1, 1)
        self.label_7 = QtGui.QLabel(self)
        self.label_7.setIndent(15)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 10, 1, 1, 1)
        self.reversedHeadAndShouldersSpinBox = QtGui.QSpinBox(self)
        self.reversedHeadAndShouldersSpinBox.setMinimum(0)
        self.reversedHeadAndShouldersSpinBox.setMaximum(100)
        self.reversedHeadAndShouldersSpinBox.setSingleStep(5)
        self.reversedHeadAndShouldersSpinBox.setProperty("value", 100)
        self.reversedHeadAndShouldersSpinBox.setObjectName(_fromUtf8("reversedHeadAndShouldersSpinBox"))
        self.gridLayout.addWidget(self.reversedHeadAndShouldersSpinBox, 14, 2, 1, 1)
        self.risingBreakawayGapSpinBox = QtGui.QSpinBox(self)
        self.risingBreakawayGapSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.risingBreakawayGapSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.risingBreakawayGapSpinBox.setMaximum(100)
        self.risingBreakawayGapSpinBox.setSingleStep(5)
        self.risingBreakawayGapSpinBox.setProperty("value", 50)
        self.risingBreakawayGapSpinBox.setObjectName(_fromUtf8("risingBreakawayGapSpinBox"))
        self.gridLayout.addWidget(self.risingBreakawayGapSpinBox, 14, 8, 1, 1)
        self.label_27 = QtGui.QLabel(self)
        self.label_27.setIndent(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 10, 7, 1, 1)
        self.risingWedgeSpinBox = QtGui.QSpinBox(self)
        self.risingWedgeSpinBox.setMinimum(-100)
        self.risingWedgeSpinBox.setMaximum(0)
        self.risingWedgeSpinBox.setSingleStep(5)
        self.risingWedgeSpinBox.setProperty("value", -80)
        self.risingWedgeSpinBox.setObjectName(_fromUtf8("risingWedgeSpinBox"))
        self.gridLayout.addWidget(self.risingWedgeSpinBox, 10, 2, 1, 1)
        self.williamsSpinBox = QtGui.QSpinBox(self)
        self.williamsSpinBox.setMaximum(100)
        self.williamsSpinBox.setSingleStep(5)
        self.williamsSpinBox.setProperty("value", 50)
        self.williamsSpinBox.setObjectName(_fromUtf8("williamsSpinBox"))
        self.gridLayout.addWidget(self.williamsSpinBox, 10, 8, 1, 1)
        self.fallingTriangleSpinBox = QtGui.QSpinBox(self)
        self.fallingTriangleSpinBox.setMinimum(-100)
        self.fallingTriangleSpinBox.setMaximum(0)
        self.fallingTriangleSpinBox.setSingleStep(5)
        self.fallingTriangleSpinBox.setProperty("value", -80)
        self.fallingTriangleSpinBox.setObjectName(_fromUtf8("fallingTriangleSpinBox"))
        self.gridLayout.addWidget(self.fallingTriangleSpinBox, 12, 2, 1, 1)
        self.fallingBreakawayGapSpinBox = QtGui.QSpinBox(self)
        self.fallingBreakawayGapSpinBox.setMinimum(-100)
        self.fallingBreakawayGapSpinBox.setMaximum(0)
        self.fallingBreakawayGapSpinBox.setSingleStep(5)
        self.fallingBreakawayGapSpinBox.setProperty("value", -50)
        self.fallingBreakawayGapSpinBox.setObjectName(_fromUtf8("fallingBreakawayGapSpinBox"))
        self.gridLayout.addWidget(self.fallingBreakawayGapSpinBox, 18, 8, 1, 1)
        self.defaultPushButton = QtGui.QPushButton(self)
        self.defaultPushButton.setStyleSheet(_fromUtf8("border-left-color: rgb(137, 255, 177);"))
        self.defaultPushButton.setObjectName(_fromUtf8("defaultPushButton"))
        self.gridLayout.addWidget(self.defaultPushButton, 18, 14, 1, 1)
        self.defaultPushButton.clicked.connect(self.defaultValues)
        self.label_42 = QtGui.QLabel(self)
        self.label_42.setIndent(15)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 6, 13, 1, 1)
        self.rsiSpinBox = QtGui.QSpinBox(self)
        self.rsiSpinBox.setMaximum(100)
        self.rsiSpinBox.setSingleStep(5)
        self.rsiSpinBox.setProperty("value", 50)
        self.rsiSpinBox.setObjectName(_fromUtf8("rsiSpinBox"))
        self.gridLayout.addWidget(self.rsiSpinBox, 9, 8, 1, 1)
        self.label_2 = QtGui.QLabel(self)
        self.label_2.setIndent(15)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 9, 1, 1, 1)
        self.symetricTriangleSpinBox = QtGui.QSpinBox(self)
        self.symetricTriangleSpinBox.setMaximum(100)
        self.symetricTriangleSpinBox.setSingleStep(5)
        self.symetricTriangleSpinBox.setProperty("value", 50)
        self.symetricTriangleSpinBox.setObjectName(_fromUtf8("symetricTriangleSpinBox"))
        self.gridLayout.addWidget(self.symetricTriangleSpinBox, 19, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self)
        self.label_30.setIndent(15)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 3, 13, 1, 1)
        self.fallingContinuationGapSpinBox = QtGui.QSpinBox(self)
        self.fallingContinuationGapSpinBox.setMinimum(-100)
        self.fallingContinuationGapSpinBox.setMaximum(0)
        self.fallingContinuationGapSpinBox.setSingleStep(5)
        self.fallingContinuationGapSpinBox.setProperty("value", -30)
        self.fallingContinuationGapSpinBox.setObjectName(_fromUtf8("fallingContinuationGapSpinBox"))
        self.gridLayout.addWidget(self.fallingContinuationGapSpinBox, 20, 8, 1, 1)
        self.label_26 = QtGui.QLabel(self)
        self.label_26.setIndent(0)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 9, 7, 1, 1)
        self.label_21 = QtGui.QLabel(self)
        self.label_21.setIndent(0)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 2, 7, 1, 1)
        self.rocSpinBox = QtGui.QSpinBox(self)
        self.rocSpinBox.setMaximum(100)
        self.rocSpinBox.setSingleStep(5)
        self.rocSpinBox.setProperty("value", 50)
        self.rocSpinBox.setObjectName(_fromUtf8("rocSpinBox"))
        self.gridLayout.addWidget(self.rocSpinBox, 5, 8, 1, 1)
        self.label_25 = QtGui.QLabel(self)
        self.label_25.setIndent(0)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 6, 7, 1, 1)
        self.label_43 = QtGui.QLabel(self)
        self.label_43.setIndent(15)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 9, 13, 1, 1)
        self.label_5 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(-5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 4)
        self.label_8 = QtGui.QLabel(self)
        self.label_8.setIndent(15)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 12, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self)
        self.label_39.setIndent(15)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 19, 7, 1, 1)
        self.label_3 = QtGui.QLabel(self)
        self.label_3.setIndent(15)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.risingExhaustionGapSpinBox = QtGui.QSpinBox(self)
        self.risingExhaustionGapSpinBox.setMinimum(-100)
        self.risingExhaustionGapSpinBox.setMaximum(0)
        self.risingExhaustionGapSpinBox.setSingleStep(5)
        self.risingExhaustionGapSpinBox.setProperty("value", -50)
        self.risingExhaustionGapSpinBox.setObjectName(_fromUtf8("risingExhaustionGapSpinBox"))
        self.gridLayout.addWidget(self.risingExhaustionGapSpinBox, 19, 8, 1, 1)
        self.label_13 = QtGui.QLabel(self)
        self.label_13.setIndent(15)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 17, 1, 1, 1)
        self.piercingSpinBox = QtGui.QSpinBox(self)
        self.piercingSpinBox.setMaximum(100)
        self.piercingSpinBox.setSingleStep(5)
        self.piercingSpinBox.setProperty("value", 5)
        self.piercingSpinBox.setObjectName(_fromUtf8("piercingSpinBox"))
        self.gridLayout.addWidget(self.piercingSpinBox, 4, 14, 1, 1)
        self.risingTriangleSpinBox = QtGui.QSpinBox(self)
        self.risingTriangleSpinBox.setMaximum(100)
        self.risingTriangleSpinBox.setSingleStep(5)
        self.risingTriangleSpinBox.setProperty("value", 80)
        self.risingTriangleSpinBox.setObjectName(_fromUtf8("risingTriangleSpinBox"))
        self.gridLayout.addWidget(self.risingTriangleSpinBox, 17, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self)
        self.label_16.setIndent(15)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 20, 1, 1, 1)
        self.positiveSignalSpinBox = QtGui.QSpinBox(self)
        self.positiveSignalSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.positiveSignalSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.positiveSignalSpinBox.setMaximum(100)
        self.positiveSignalSpinBox.setSingleStep(5)
        self.positiveSignalSpinBox.setProperty("value", 50)
        self.positiveSignalSpinBox.setObjectName(_fromUtf8("positiveSignalSpinBox"))
        self.gridLayout.addWidget(self.positiveSignalSpinBox, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self)
        self.label_20.setIndent(0)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 1, 7, 1, 1)
        self.trendSpinBox = QtGui.QSpinBox(self)
        self.trendSpinBox.setMaximum(100)
        self.trendSpinBox.setSingleStep(5)
        self.trendSpinBox.setProperty("value", 100)
        self.trendSpinBox.setObjectName(_fromUtf8("trendSpinBox"))
        self.gridLayout.addWidget(self.trendSpinBox, 2, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self)
        self.label_24.setIndent(0)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 5, 7, 1, 1)
        self.label_40 = QtGui.QLabel(self)
        self.label_40.setIndent(15)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 20, 7, 1, 1)
        self.bollingerSpinBox = QtGui.QSpinBox(self)
        self.bollingerSpinBox.setMaximum(100)
        self.bollingerSpinBox.setSingleStep(5)
        self.bollingerSpinBox.setProperty("value", 50)
        self.bollingerSpinBox.setObjectName(_fromUtf8("bollingerSpinBox"))
        self.gridLayout.addWidget(self.bollingerSpinBox, 3, 8, 1, 1)
        self.label_44 = QtGui.QLabel(self)
        self.label_44.setIndent(15)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 10, 13, 1, 1)
        self.label_38 = QtGui.QLabel(self)
        self.label_38.setIndent(15)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 18, 7, 1, 1)
        self.label_34 = QtGui.QLabel(self)
        self.label_34.setIndent(15)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 14, 7, 1, 1)
        self.tripleTopSpinBox = QtGui.QSpinBox(self)
        self.tripleTopSpinBox.setMinimum(-100)
        self.tripleTopSpinBox.setMaximum(0)
        self.tripleTopSpinBox.setSingleStep(5)
        self.tripleTopSpinBox.setProperty("value", -100)
        self.tripleTopSpinBox.setObjectName(_fromUtf8("tripleTopSpinBox"))
        self.gridLayout.addWidget(self.tripleTopSpinBox, 9, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self)
        self.label_11.setIndent(15)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 15, 1, 1, 1)
        self.tripleBottomSpinBox = QtGui.QSpinBox(self)
        self.tripleBottomSpinBox.setMaximum(100)
        self.tripleBottomSpinBox.setSingleStep(5)
        self.tripleBottomSpinBox.setProperty("value", 100)
        self.tripleBottomSpinBox.setObjectName(_fromUtf8("tripleBottomSpinBox"))
        self.gridLayout.addWidget(self.tripleBottomSpinBox, 15, 2, 1, 1)
        self.morningStarSpinBox = QtGui.QSpinBox(self)
        self.morningStarSpinBox.setMaximum(100)
        self.morningStarSpinBox.setSingleStep(5)
        self.morningStarSpinBox.setProperty("value", 10)
        self.morningStarSpinBox.setObjectName(_fromUtf8("morningStarSpinBox"))
        self.gridLayout.addWidget(self.morningStarSpinBox, 3, 14, 1, 1)
        self.fallingWedgeSpinBox = QtGui.QSpinBox(self)
        self.fallingWedgeSpinBox.setMaximum(100)
        self.fallingWedgeSpinBox.setSingleStep(5)
        self.fallingWedgeSpinBox.setProperty("value", 80)
        self.fallingWedgeSpinBox.setObjectName(_fromUtf8("fallingWedgeSpinBox"))
        self.gridLayout.addWidget(self.fallingWedgeSpinBox, 16, 2, 1, 1)
        self.eveningStarSpinBox = QtGui.QSpinBox(self)
        self.eveningStarSpinBox.setMinimum(-100)
        self.eveningStarSpinBox.setMaximum(0)
        self.eveningStarSpinBox.setSingleStep(5)
        self.eveningStarSpinBox.setProperty("value", -10)
        self.eveningStarSpinBox.setObjectName(_fromUtf8("eveningStarSpinBox"))
        self.gridLayout.addWidget(self.eveningStarSpinBox, 9, 14, 1, 1)
        self.label_12 = QtGui.QLabel(self)
        self.label_12.setIndent(15)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 16, 1, 1, 1)
        self.headAndShouldersSpinBox = QtGui.QSpinBox(self)
        self.headAndShouldersSpinBox.setMinimum(-100)
        self.headAndShouldersSpinBox.setMaximum(0)
        self.headAndShouldersSpinBox.setSingleStep(5)
        self.headAndShouldersSpinBox.setProperty("value", -100)
        self.headAndShouldersSpinBox.setObjectName(_fromUtf8("headAndShouldersSpinBox"))
        self.gridLayout.addWidget(self.headAndShouldersSpinBox, 6, 2, 1, 1)
        self.momentumSpinBox = QtGui.QSpinBox(self)
        self.momentumSpinBox.setMaximum(100)
        self.momentumSpinBox.setSingleStep(5)
        self.momentumSpinBox.setProperty("value", 50)
        self.momentumSpinBox.setObjectName(_fromUtf8("momentumSpinBox"))
        self.gridLayout.addWidget(self.momentumSpinBox, 4, 8, 1, 1)
        self.darkCloudSpinBox = QtGui.QSpinBox(self)
        self.darkCloudSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.darkCloudSpinBox.setMinimum(-100)
        self.darkCloudSpinBox.setMaximum(0)
        self.darkCloudSpinBox.setSingleStep(5)
        self.darkCloudSpinBox.setProperty("value", -5)
        self.darkCloudSpinBox.setObjectName(_fromUtf8("darkCloudSpinBox"))
        self.gridLayout.addWidget(self.darkCloudSpinBox, 10, 14, 1, 1)
        self.label_10 = QtGui.QLabel(self)
        self.label_10.setIndent(15)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 14, 1, 1, 1)
        self.rectangleSpinBox = QtGui.QSpinBox(self)
        self.rectangleSpinBox.setMaximum(100)
        self.rectangleSpinBox.setSingleStep(5)
        self.rectangleSpinBox.setProperty("value", 30)
        self.rectangleSpinBox.setObjectName(_fromUtf8("rectangleSpinBox"))
        self.gridLayout.addWidget(self.rectangleSpinBox, 20, 2, 1, 1)
        self.rectangleCheckBox = QtGui.QCheckBox(self)
        self.rectangleCheckBox.setText(_fromUtf8(""))
        self.rectangleCheckBox.setObjectName(_fromUtf8("rectangleCheckBox"))
        self.gridLayout.addWidget(self.rectangleCheckBox, 20, 0, 1, 1)
        self.momentumCheckBox = QtGui.QCheckBox(self)
        self.momentumCheckBox.setText(_fromUtf8(""))
        self.momentumCheckBox.setObjectName(_fromUtf8("momentumCheckBox"))
        self.gridLayout.addWidget(self.momentumCheckBox, 4, 6, 1, 1)
        self.rocCheckBox = QtGui.QCheckBox(self)
        self.rocCheckBox.setText(_fromUtf8(""))
        self.rocCheckBox.setObjectName(_fromUtf8("rocCheckBox"))
        self.gridLayout.addWidget(self.rocCheckBox, 5, 6, 1, 1)
        self.risingBreakawayGapCheckBox = QtGui.QCheckBox(self)
        self.risingBreakawayGapCheckBox.setText(_fromUtf8(""))
        self.risingBreakawayGapCheckBox.setObjectName(_fromUtf8("risingBreakawayGapCheckBox"))
        self.gridLayout.addWidget(self.risingBreakawayGapCheckBox, 14, 6, 1, 1)
        self.rsiCheckBox = QtGui.QCheckBox(self)
        self.rsiCheckBox.setText(_fromUtf8(""))
        self.rsiCheckBox.setObjectName(_fromUtf8("rsiCheckBox"))
        self.gridLayout.addWidget(self.rsiCheckBox, 9, 6, 1, 1)
        self.headAndShouldersCheckBox = QtGui.QCheckBox(self)
        self.headAndShouldersCheckBox.setText(_fromUtf8(""))
        self.headAndShouldersCheckBox.setObjectName(_fromUtf8("headAndShouldersCheckBox"))
        self.gridLayout.addWidget(self.headAndShouldersCheckBox, 6, 0, 1, 1)
        self.risingContinuationGapCheckBox = QtGui.QCheckBox(self)
        self.risingContinuationGapCheckBox.setText(_fromUtf8(""))
        self.risingContinuationGapCheckBox.setObjectName(_fromUtf8("risingContinuationGapCheckBox"))
        self.gridLayout.addWidget(self.risingContinuationGapCheckBox, 15, 6, 1, 1)
        self.symetricTriangleCheckBox = QtGui.QCheckBox(self)
        self.symetricTriangleCheckBox.setText(_fromUtf8(""))
        self.symetricTriangleCheckBox.setObjectName(_fromUtf8("symetricTriangleCheckBox"))
        self.gridLayout.addWidget(self.symetricTriangleCheckBox, 19, 0, 1, 1)
        self.tripleTopCheckBox = QtGui.QCheckBox(self)
        self.tripleTopCheckBox.setText(_fromUtf8(""))
        self.tripleTopCheckBox.setObjectName(_fromUtf8("tripleTopCheckBox"))
        self.gridLayout.addWidget(self.tripleTopCheckBox, 9, 0, 1, 1)
        self.risingWedgeCheckBox = QtGui.QCheckBox(self)
        self.risingWedgeCheckBox.setText(_fromUtf8(""))
        self.risingWedgeCheckBox.setObjectName(_fromUtf8("risingWedgeCheckBox"))
        self.gridLayout.addWidget(self.risingWedgeCheckBox, 10, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 2)
        self.reversalOfFallingTrendCheckBox = QtGui.QCheckBox(self)
        self.reversalOfFallingTrendCheckBox.setText(_fromUtf8(""))
        self.reversalOfFallingTrendCheckBox.setObjectName(_fromUtf8("reversalOfFallingTrendCheckBox"))
        self.gridLayout.addWidget(self.reversalOfFallingTrendCheckBox, 13, 0, 1, 1)
        self.reversedHeadAndShouldersCheckBox = QtGui.QCheckBox(self)
        self.reversedHeadAndShouldersCheckBox.setText(_fromUtf8(""))
        self.reversedHeadAndShouldersCheckBox.setObjectName(_fromUtf8("reversedHeadAndShouldersCheckBox"))
        self.gridLayout.addWidget(self.reversedHeadAndShouldersCheckBox, 14, 0, 1, 1)
        self.tripleBottomCheckBox = QtGui.QCheckBox(self)
        self.tripleBottomCheckBox.setText(_fromUtf8(""))
        self.tripleBottomCheckBox.setObjectName(_fromUtf8("tripleBottomCheckBox"))
        self.gridLayout.addWidget(self.tripleBottomCheckBox, 15, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 3, 0, 1, 3)
        self.fallingWedgeCheckBox = QtGui.QCheckBox(self)
        self.fallingWedgeCheckBox.setText(_fromUtf8(""))
        self.fallingWedgeCheckBox.setObjectName(_fromUtf8("fallingWedgeCheckBox"))
        self.gridLayout.addWidget(self.fallingWedgeCheckBox, 16, 0, 1, 1)
        self.fallingContinuationGapCheckBox = QtGui.QCheckBox(self)
        self.fallingContinuationGapCheckBox.setText(_fromUtf8(""))
        self.fallingContinuationGapCheckBox.setObjectName(_fromUtf8("fallingContinuationGapCheckBox"))
        self.gridLayout.addWidget(self.fallingContinuationGapCheckBox, 20, 6, 1, 1)
        self.formationsCheckBox = QtGui.QCheckBox(self)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.formationsCheckBox.setFont(font)
        self.formationsCheckBox.setText(_fromUtf8(""))
        self.formationsCheckBox.setCheckable(True)
        self.formationsCheckBox.setTristate(False)
        self.formationsCheckBox.setObjectName(_fromUtf8("formationsCheckBox"))
        self.gridLayout.addWidget(self.formationsCheckBox, 4, 0, 1, 1)
        self.bollingerCheckBox = QtGui.QCheckBox(self)
        self.bollingerCheckBox.setText(_fromUtf8(""))
        self.bollingerCheckBox.setObjectName(_fromUtf8("bollingerCheckBox"))
        self.gridLayout.addWidget(self.bollingerCheckBox, 3, 6, 1, 1)
        self.gapsCheckBox = QtGui.QCheckBox(self)
        self.gapsCheckBox.setText(_fromUtf8(""))
        self.gapsCheckBox.setObjectName(_fromUtf8("gapsCheckBox"))
        self.gridLayout.addWidget(self.gapsCheckBox, 12, 6, 1, 1)
        self.indicatorsAndOscilatorsCheckBox = QtGui.QCheckBox(self)
        self.indicatorsAndOscilatorsCheckBox.setText(_fromUtf8(""))
        self.indicatorsAndOscilatorsCheckBox.setObjectName(_fromUtf8("indicatorsAndOscilatorsCheckBox"))
        self.gridLayout.addWidget(self.indicatorsAndOscilatorsCheckBox, 0, 6, 1, 1)
        self.newHighNewLowCheckBox = QtGui.QCheckBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newHighNewLowCheckBox.sizePolicy().hasHeightForWidth())
        self.newHighNewLowCheckBox.setSizePolicy(sizePolicy)
        self.newHighNewLowCheckBox.setText(_fromUtf8(""))
        self.newHighNewLowCheckBox.setObjectName(_fromUtf8("newHighNewLowCheckBox"))
        self.gridLayout.addWidget(self.newHighNewLowCheckBox, 2, 6, 1, 1)
        self.cciCheckBox = QtGui.QCheckBox(self)
        self.cciCheckBox.setText(_fromUtf8(""))
        self.cciCheckBox.setObjectName(_fromUtf8("cciCheckBox"))
        self.gridLayout.addWidget(self.cciCheckBox, 6, 6, 1, 1)
        self.fallingExhaustionGapCheckBox = QtGui.QCheckBox(self)
        self.fallingExhaustionGapCheckBox.setText(_fromUtf8(""))
        self.fallingExhaustionGapCheckBox.setObjectName(_fromUtf8("fallingExhaustionGapCheckBox"))
        self.gridLayout.addWidget(self.fallingExhaustionGapCheckBox, 16, 6, 1, 1)
        self.line = QtGui.QFrame(self)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 5, 2, 1)
        self.williamsCheckBox = QtGui.QCheckBox(self)
        self.williamsCheckBox.setText(_fromUtf8(""))
        self.williamsCheckBox.setObjectName(_fromUtf8("williamsCheckBox"))
        self.gridLayout.addWidget(self.williamsCheckBox, 10, 6, 1, 1)
        self.risingGapsCheckBox = QtGui.QCheckBox(self)
        self.risingGapsCheckBox.setText(_fromUtf8(""))
        self.risingGapsCheckBox.setObjectName(_fromUtf8("risingGapsCheckBox"))
        self.gridLayout.addWidget(self.risingGapsCheckBox, 13, 6, 1, 1)
        self.risingExhaustionGapCheckBox = QtGui.QCheckBox(self)
        self.risingExhaustionGapCheckBox.setText(_fromUtf8(""))
        self.risingExhaustionGapCheckBox.setObjectName(_fromUtf8("risingExhaustionGapCheckBox"))
        self.gridLayout.addWidget(self.risingExhaustionGapCheckBox, 19, 6, 1, 1)
        self.fallingBreakawayGapCheckBox = QtGui.QCheckBox(self)
        self.fallingBreakawayGapCheckBox.setText(_fromUtf8(""))
        self.fallingBreakawayGapCheckBox.setObjectName(_fromUtf8("fallingBreakawayGapCheckBox"))
        self.gridLayout.addWidget(self.fallingBreakawayGapCheckBox, 18, 6, 1, 1)
        self.fallingGapsCheckBox = QtGui.QCheckBox(self)
        self.fallingGapsCheckBox.setText(_fromUtf8(""))
        self.fallingGapsCheckBox.setObjectName(_fromUtf8("fallingGapsCheckBox"))
        self.gridLayout.addWidget(self.fallingGapsCheckBox, 17, 6, 1, 1)
        self.bull3CheckBox = QtGui.QCheckBox(self)
        self.bull3CheckBox.setText(_fromUtf8(""))
        self.bull3CheckBox.setObjectName(_fromUtf8("bull3CheckBox"))
        self.gridLayout.addWidget(self.bull3CheckBox, 2, 12, 1, 1)
        self.buySignalCheckBox = QtGui.QCheckBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buySignalCheckBox.sizePolicy().hasHeightForWidth())
        self.buySignalCheckBox.setSizePolicy(sizePolicy)
        self.buySignalCheckBox.setText(_fromUtf8(""))
        self.buySignalCheckBox.setObjectName(_fromUtf8("buySignalCheckBox"))
        self.gridLayout.addWidget(self.buySignalCheckBox, 1, 12, 1, 1)
        self.morningStarCheckBox = QtGui.QCheckBox(self)
        self.morningStarCheckBox.setText(_fromUtf8(""))
        self.morningStarCheckBox.setObjectName(_fromUtf8("morningStarCheckBox"))
        self.gridLayout.addWidget(self.morningStarCheckBox, 3, 12, 1, 1)
        self.piercingCheckBox = QtGui.QCheckBox(self)
        self.piercingCheckBox.setText(_fromUtf8(""))
        self.piercingCheckBox.setObjectName(_fromUtf8("piercingCheckBox"))
        self.gridLayout.addWidget(self.piercingCheckBox, 4, 12, 1, 1)
        self.sellSignalCheckBox = QtGui.QCheckBox(self)
        self.sellSignalCheckBox.setText(_fromUtf8(""))
        self.sellSignalCheckBox.setObjectName(_fromUtf8("sellSignalCheckBox"))
        self.gridLayout.addWidget(self.sellSignalCheckBox, 5, 12, 1, 1)
        self.bear3CheckBox = QtGui.QCheckBox(self)
        self.bear3CheckBox.setText(_fromUtf8(""))
        self.bear3CheckBox.setObjectName(_fromUtf8("bear3CheckBox"))
        self.gridLayout.addWidget(self.bear3CheckBox, 6, 12, 1, 1)
        self.eveningStarCheckBox = QtGui.QCheckBox(self)
        self.eveningStarCheckBox.setText(_fromUtf8(""))
        self.eveningStarCheckBox.setObjectName(_fromUtf8("eveningStarCheckBox"))
        self.gridLayout.addWidget(self.eveningStarCheckBox, 9, 12, 1, 1)
        self.darkCloudCheckBox = QtGui.QCheckBox(self)
        self.darkCloudCheckBox.setText(_fromUtf8(""))
        self.darkCloudCheckBox.setObjectName(_fromUtf8("darkCloudCheckBox"))
        self.gridLayout.addWidget(self.darkCloudCheckBox, 10, 12, 1, 1)
        self.candlesticPatternsCheckBox = QtGui.QCheckBox(self)
        self.candlesticPatternsCheckBox.setText(_fromUtf8(""))
        self.candlesticPatternsCheckBox.setObjectName(_fromUtf8("candlesticPatternsCheckBox"))
        self.gridLayout.addWidget(self.candlesticPatternsCheckBox, 0, 12, 1, 1)
        self.headAndShouldersLineStyle = LineStyleComboBox()
        self.headAndShouldersLineStyle.setObjectName(_fromUtf8("headAndShouldersLineStyle"))
        self.gridLayout.addWidget(self.headAndShouldersLineStyle, 6, 3, 1, 1)
        self.risingWedgeLineStyle = LineStyleComboBox()
        self.risingWedgeLineStyle.setObjectName(_fromUtf8("risingWedgeLineStyle"))
        self.gridLayout.addWidget(self.risingWedgeLineStyle, 10, 3, 1, 1)
        self.risingWedgeColor = ColorComboBox()
        self.risingWedgeColor.setObjectName(_fromUtf8("risingWedgeColor"))
        self.gridLayout.addWidget(self.risingWedgeColor, 10, 4, 1, 1)
        self.tripleTopLineStyle = LineStyleComboBox()
        self.tripleTopLineStyle.setObjectName(_fromUtf8("tripleTopLineStyle"))
        self.gridLayout.addWidget(self.tripleTopLineStyle, 9, 3, 1, 1)
        self.headAndShouldersColor = ColorComboBox()
        self.headAndShouldersColor.setObjectName(_fromUtf8("headAndShouldersColor"))
        self.gridLayout.addWidget(self.headAndShouldersColor, 6, 4, 1, 1)
        self.rectangleColor = ColorComboBox()
        self.rectangleColor.setObjectName(_fromUtf8("rectangleColor"))
        self.gridLayout.addWidget(self.rectangleColor, 20, 4, 1, 1)
        self.newHighNewLowColor = ColorComboBox()
        self.newHighNewLowColor.setObjectName(_fromUtf8("newHighNewLowColor"))
        self.gridLayout.addWidget(self.newHighNewLowColor, 2, 10, 1, 1)
        self.fallingTriangleLineStyle = LineStyleComboBox()
        self.fallingTriangleLineStyle.setObjectName(_fromUtf8("fallingTriangleLineStyle"))
        self.gridLayout.addWidget(self.fallingTriangleLineStyle, 12, 3, 1, 1)
        self.fallingTriangleColor = ColorComboBox()
        self.fallingTriangleColor.setObjectName(_fromUtf8("fallingTriangleColor"))
        self.gridLayout.addWidget(self.fallingTriangleColor, 12, 4, 1, 1)
        self.tripleBottomLineStyle = LineStyleComboBox()
        self.tripleBottomLineStyle.setObjectName(_fromUtf8("tripleBottomLineStyle"))
        self.gridLayout.addWidget(self.tripleBottomLineStyle, 15, 3, 1, 1)
        self.reversedHeadAndShouldersLineStyle = LineStyleComboBox()
        self.reversedHeadAndShouldersLineStyle.setObjectName(_fromUtf8("reversedHeadAndShouldersLineStyle"))
        self.gridLayout.addWidget(self.reversedHeadAndShouldersLineStyle, 14, 3, 1, 1)
        self.reversedHeadAndShouldersColor = ColorComboBox()
        self.reversedHeadAndShouldersColor.setObjectName(_fromUtf8("reversedHeadAndShouldersColor"))
        self.gridLayout.addWidget(self.reversedHeadAndShouldersColor, 14, 4, 1, 1)
        self.tripleBottomColor = ColorComboBox()
        self.tripleBottomColor.setObjectName(_fromUtf8("tripleBottomColor"))
        self.gridLayout.addWidget(self.tripleBottomColor, 15, 4, 1, 1)
        self.fallingWedgeLineStyle = LineStyleComboBox()
        self.fallingWedgeLineStyle.setObjectName(_fromUtf8("fallingWedgeLineStyle"))
        self.gridLayout.addWidget(self.fallingWedgeLineStyle, 16, 3, 1, 1)
        self.risingTriangleLineStyle = LineStyleComboBox()
        self.risingTriangleLineStyle.setObjectName(_fromUtf8("risingTriangleLineStyle"))
        self.gridLayout.addWidget(self.risingTriangleLineStyle, 17, 3, 1, 1)
        self.fallingWedgeColor = ColorComboBox()
        self.fallingWedgeColor.setObjectName(_fromUtf8("fallingWedgeColor"))
        self.gridLayout.addWidget(self.fallingWedgeColor, 16, 4, 1, 1)
        self.risingTriangleColor = ColorComboBox()
        self.risingTriangleColor.setObjectName(_fromUtf8("risingTriangleColor"))
        self.gridLayout.addWidget(self.risingTriangleColor, 17, 4, 1, 1)
        self.symetricTriangleLineStyle = LineStyleComboBox()
        self.symetricTriangleLineStyle.setObjectName(_fromUtf8("symetricTriangleLineStyle"))
        self.gridLayout.addWidget(self.symetricTriangleLineStyle, 19, 3, 1, 1)
        self.symetricTriangleColor = ColorComboBox()
        self.symetricTriangleColor.setObjectName(_fromUtf8("symetricTriangleColor"))
        self.gridLayout.addWidget(self.symetricTriangleColor, 19, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_14.setIndent(0)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 18, 1, 1, 4)
        self.rectangleLineStyle = LineStyleComboBox()
        self.rectangleLineStyle.setObjectName(_fromUtf8("rectangleLineStyle"))
        self.gridLayout.addWidget(self.rectangleLineStyle, 20, 3, 1, 1)
        self.newHighNewLowLineStyle = LineStyleComboBox()
        self.newHighNewLowLineStyle.setObjectName(_fromUtf8("newHighNewLowLineStyle"))
        self.gridLayout.addWidget(self.newHighNewLowLineStyle, 2, 9, 1, 1)
        self.bollingerColor = ColorComboBox()
        self.bollingerColor.setObjectName(_fromUtf8("bollingerColor"))
        self.gridLayout.addWidget(self.bollingerColor, 3, 10, 1, 1)
        self.oscilatorsColor = ColorComboBox()
        self.oscilatorsColor.setObjectName(_fromUtf8("oscilatorsColor"))
        self.gridLayout.addWidget(self.oscilatorsColor, 1, 10, 1, 1)
        self.bollingerLineStyle = LineStyleComboBox()
        self.bollingerLineStyle.setObjectName(_fromUtf8("bollingerLineStyle"))
        self.gridLayout.addWidget(self.bollingerLineStyle, 3, 9, 1, 1)
        self.momentumLineStyle = LineStyleComboBox()
        self.momentumLineStyle.setObjectName(_fromUtf8("momentumLineStyle"))
        self.gridLayout.addWidget(self.momentumLineStyle, 4, 9, 1, 1)
        self.rocLineStyle = LineStyleComboBox()
        self.rocLineStyle.setObjectName(_fromUtf8("rocLineStyle"))
        self.gridLayout.addWidget(self.rocLineStyle, 5, 9, 1, 1)
        self.momentumColor = ColorComboBox()
        self.momentumColor.setObjectName(_fromUtf8("momentumColor"))
        self.gridLayout.addWidget(self.momentumColor, 4, 10, 1, 1)
        self.rocColor = ColorComboBox()
        self.rocColor.setObjectName(_fromUtf8("rocColor"))
        self.gridLayout.addWidget(self.rocColor, 5, 10, 1, 1)
        self.rsiColor = ColorComboBox()
        self.rsiColor.setObjectName(_fromUtf8("rsiColor"))
        self.gridLayout.addWidget(self.rsiColor, 9, 10, 1, 1)
        self.cciLineStyle = LineStyleComboBox()
        self.cciLineStyle.setObjectName(_fromUtf8("cciLineStyle"))
        self.gridLayout.addWidget(self.cciLineStyle, 6, 9, 1, 1)
        self.cciColor = ColorComboBox()
        self.cciColor.setObjectName(_fromUtf8("cciColor"))
        self.gridLayout.addWidget(self.cciColor, 6, 10, 1, 1)
        self.rsiLineStyle = LineStyleComboBox()
        self.rsiLineStyle.setObjectName(_fromUtf8("rsiLineStyle"))
        self.gridLayout.addWidget(self.rsiLineStyle, 9, 9, 1, 1)
        self.williamsLineStyle = LineStyleComboBox()
        self.williamsLineStyle.setObjectName(_fromUtf8("williamsLineStyle"))
        self.gridLayout.addWidget(self.williamsLineStyle, 10, 9, 1, 1)
        self.williamsColor = ColorComboBox()
        self.williamsColor.setObjectName(_fromUtf8("williamsColor"))
        self.gridLayout.addWidget(self.williamsColor, 10, 10, 1, 1)
        self.risingBreakawayGapLineStyle = LineStyleComboBox()
        self.risingBreakawayGapLineStyle.setObjectName(_fromUtf8("risingBreakawayGapLineStyle"))
        self.gridLayout.addWidget(self.risingBreakawayGapLineStyle, 14, 9, 1, 1)
        self.fallingExhaustionGapLineStyle = LineStyleComboBox()
        self.fallingExhaustionGapLineStyle.setObjectName(_fromUtf8("fallingExhaustionGapLineStyle"))
        self.gridLayout.addWidget(self.fallingExhaustionGapLineStyle, 16, 9, 1, 1)
        self.risingBreakawayGapColor = ColorComboBox()
        self.risingBreakawayGapColor.setObjectName(_fromUtf8("risingBreakawayGapColor"))
        self.gridLayout.addWidget(self.risingBreakawayGapColor, 14, 10, 1, 1)
        self.risingContinuationGapLineStyle = LineStyleComboBox()
        self.risingContinuationGapLineStyle.setObjectName(_fromUtf8("risingContinuationGapLineStyle"))
        self.gridLayout.addWidget(self.risingContinuationGapLineStyle, 15, 9, 1, 1)
        self.risingContinuationGapColor = ColorComboBox()
        self.risingContinuationGapColor.setObjectName(_fromUtf8("risingContinuationGapColor"))
        self.gridLayout.addWidget(self.risingContinuationGapColor, 15, 10, 1, 1)
        self.fallingBreakawayGapColor = ColorComboBox()
        self.fallingBreakawayGapColor.setObjectName(_fromUtf8("fallingBreakawayGapColor"))
        self.gridLayout.addWidget(self.fallingBreakawayGapColor, 18, 10, 1, 1)
        self.fallingExhaustionGapColor = ColorComboBox()
        self.fallingExhaustionGapColor.setObjectName(_fromUtf8("fallingExhaustionGapColor"))
        self.gridLayout.addWidget(self.fallingExhaustionGapColor, 16, 10, 1, 1)
        self.fallingBreakawayGapLineStyle = LineStyleComboBox()
        self.fallingBreakawayGapLineStyle.setObjectName(_fromUtf8("fallingBreakawayGapLineStyle"))
        self.gridLayout.addWidget(self.fallingBreakawayGapLineStyle, 18, 9, 1, 1)
        self.risingExhaustionGapLineStyle = LineStyleComboBox()
        self.risingExhaustionGapLineStyle.setObjectName(_fromUtf8("risingExhaustionGapLineStyle"))
        self.gridLayout.addWidget(self.risingExhaustionGapLineStyle, 19, 9, 1, 1)
        self.risingExhaustionGapColor = ColorComboBox()
        self.risingExhaustionGapColor.setObjectName(_fromUtf8("risingExhaustionGapColor"))
        self.gridLayout.addWidget(self.risingExhaustionGapColor, 19, 10, 1, 1)
        self.fallingContinuationGapLineStyle = LineStyleComboBox()
        self.fallingContinuationGapLineStyle.setObjectName(_fromUtf8("fallingContinuationGapLineStyle"))
        self.gridLayout.addWidget(self.fallingContinuationGapLineStyle, 20, 9, 1, 1)
        self.fallingContinuationGapColor = ColorComboBox()
        self.fallingContinuationGapColor.setObjectName(_fromUtf8("fallingContinuationGapColor"))
        self.gridLayout.addWidget(self.fallingContinuationGapColor, 20, 10, 1, 1)
        self.bull3Color = ColorComboBox()
        self.bull3Color.setObjectName(_fromUtf8("bull3Color"))
        self.gridLayout.addWidget(self.bull3Color, 2, 16, 1, 1)
        self.morningStarLineStyle = LineStyleComboBox()
        self.morningStarLineStyle.setObjectName(_fromUtf8("morningStarLineStyle"))
        self.gridLayout.addWidget(self.morningStarLineStyle, 3, 15, 1, 1)
        self.morningStarColor = ColorComboBox()
        self.morningStarColor.setObjectName(_fromUtf8("morningStarColor"))
        self.gridLayout.addWidget(self.morningStarColor, 3, 16, 1, 1)
        self.piercingLineStyle = LineStyleComboBox()
        self.piercingLineStyle.setObjectName(_fromUtf8("piercingLineStyle"))
        self.gridLayout.addWidget(self.piercingLineStyle, 4, 15, 1, 1)
        self.piercingColor = ColorComboBox()
        self.piercingColor.setObjectName(_fromUtf8("piercingColor"))
        self.gridLayout.addWidget(self.piercingColor, 4, 16, 1, 1)
        self.bear3LineStyle = LineStyleComboBox()
        self.bear3LineStyle.setObjectName(_fromUtf8("bear3LineStyle"))
        self.gridLayout.addWidget(self.bear3LineStyle, 6, 15, 1, 1)
        self.bear3Color = ColorComboBox()
        self.bear3Color.setObjectName(_fromUtf8("bear3Color"))
        self.gridLayout.addWidget(self.bear3Color, 6, 16, 1, 1)
        self.eveningStarLineStyle = LineStyleComboBox()
        self.eveningStarLineStyle.setObjectName(_fromUtf8("eveningStarLineStyle"))
        self.gridLayout.addWidget(self.eveningStarLineStyle, 9, 15, 1, 1)
        self.eveningStarColor = ColorComboBox()
        self.eveningStarColor.setObjectName(_fromUtf8("eveningStarColor"))
        self.gridLayout.addWidget(self.eveningStarColor, 9, 16, 1, 1)
        self.darkCloudLineStyle = LineStyleComboBox()
        self.darkCloudLineStyle.setObjectName(_fromUtf8("darkCloudLineStyle"))
        self.gridLayout.addWidget(self.darkCloudLineStyle, 10, 15, 1, 1)
        self.darkCloudColor = ColorComboBox()
        self.darkCloudColor.setObjectName(_fromUtf8("darkCloudColor"))
        self.gridLayout.addWidget(self.darkCloudColor, 10, 16, 1, 1)
        self.label_41 = QtGui.QLabel(self)
        self.label_41.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 5, 13, 1, 4)
        self.label_28 = QtGui.QLabel(self)
        self.label_28.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 1, 13, 1, 4)
        self.label_4 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 13, 1, 4)
        self.label_19 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 0, 7, 1, 4)
        self.label_32 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 12, 7, 1, 4)
        self.label_33 = QtGui.QLabel(self)
        self.label_33.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 13, 7, 1, 4)
        self.label_37 = QtGui.QLabel(self)
        self.label_37.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_37.setIndent(0)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 17, 7, 1, 4)

        self.flagPennantCheckBox = QtGui.QCheckBox(self)
        self.flagPennantCheckBox.setText(_fromUtf8(""))
        self.flagPennantCheckBox.setObjectName(_fromUtf8("flagPennantCheckBox"))
        self.gridLayout.addWidget(self.flagPennantCheckBox, 21, 0, 1, 1)
        self.flagPennantSpinBox = QtGui.QSpinBox(self)
        self.flagPennantSpinBox.setMaximum(100)
        self.flagPennantSpinBox.setSingleStep(5)
        self.flagPennantSpinBox.setProperty("value", 20)
        self.flagPennantSpinBox.setObjectName(_fromUtf8("flagPennantSpinBox"))
        self.gridLayout.addWidget(self.flagPennantSpinBox, 21, 2, 1, 1)
        self.flagPennantLineStyle = LineStyleComboBox()
        self.flagPennantLineStyle.setObjectName(_fromUtf8("flagPennantLineStyle"))
        self.gridLayout.addWidget(self.flagPennantLineStyle, 21, 3, 1, 1)
        self.flagPennantColor = ColorComboBox()
        self.flagPennantColor.setObjectName(_fromUtf8("flagPennantColor"))
        self.gridLayout.addWidget(self.flagPennantColor, 21, 4, 1, 1)

        self.retranslateUi()
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reversalOfRisingTrendCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.headAndShouldersCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingWedgeCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingTriangleCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingTriangleCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.continuationOfTrendCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.symetricTriangleCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rectangleCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tripleTopCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.headAndShouldersCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tripleTopCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingWedgeCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingTriangleCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reversedHeadAndShouldersCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tripleBottomCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingWedgeCheckBox.setOn)
        # QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingTriangleCheckBox.setOn)
        # QtCore.QObject.connect(self.continuationOfTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.symetricTriangleCheckBox.setOn)
        # QtCore.QObject.connect(self.continuationOfTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rectangleCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.oscilatorsCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.newHighNewLowCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bollingerCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.momentumCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rocCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cciCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rsiCheckBox.setOn)
        # QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.williamsCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingGapsCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingBreakawayGapCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingContinuationGapCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingExhaustionGapCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingGapsCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingBreakawayGapCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingExhaustionGapCheckBox.setOn)
        # QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingContinuationGapCheckBox.setOn)
        # QtCore.QObject.connect(self.risingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingBreakawayGapCheckBox.setOn)
        # QtCore.QObject.connect(self.risingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingContinuationGapCheckBox.setOn)
        # QtCore.QObject.connect(self.risingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingExhaustionGapCheckBox.setOn)
        # QtCore.QObject.connect(self.fallingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingBreakawayGapCheckBox.setOn)
        # QtCore.QObject.connect(self.fallingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingExhaustionGapCheckBox.setOn)
        # QtCore.QObject.connect(self.fallingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingContinuationGapCheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.buySignalCheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bull3CheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.morningStarCheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.piercingCheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.sellSignalCheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bear3CheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.eveningStarCheckBox.setOn)
        # QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.darkCloudCheckBox.setOn)
        # QtCore.QObject.connect(self.buySignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bull3CheckBox.setOn)
        # QtCore.QObject.connect(self.buySignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.morningStarCheckBox.setOn)
        # QtCore.QObject.connect(self.buySignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.piercingCheckBox.setOn)
        # QtCore.QObject.connect(self.sellSignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.darkCloudCheckBox.setOn)
        # QtCore.QObject.connect(self.sellSignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bear3CheckBox.setOn)
        # QtCore.QObject.connect(self.sellSignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.eveningStarCheckBox.setOn)
        # QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.flagPennantCheckBox.setOn)
        # QtCore.QObject.connect(self.continuationOfTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.flagPennantCheckBox.setOn)
        QtCore.QMetaObject.connectSlotsByName(self)
        

        """ set Tool Tip My"""
        
        self.headAndShouldersCheckBox.setToolTip("ON/OFF")
        self.tripleTopCheckBox.setToolTip("ON/OFF")
        self.risingWedgeCheckBox.setToolTip("ON/OFF")
        self.fallingTriangleCheckBox.setToolTip("ON/OFF")
        self.reversedHeadAndShouldersCheckBox.setToolTip("ON/OFF")
        self.tripleBottomCheckBox.setToolTip("ON/OFF")
        self.fallingWedgeCheckBox.setToolTip("ON/OFF")
        self.risingTriangleCheckBox.setToolTip("ON/OFF")
        self.symetricTriangleCheckBox.setToolTip("ON/OFF")
        self.rectangleCheckBox.setToolTip("ON/OFF")
        self.oscilatorsCheckBox.setToolTip("ON/OFF")
        self.newHighNewLowCheckBox.setToolTip("ON/OFF")
        self.bollingerCheckBox.setToolTip("ON/OFF")
        self.momentumCheckBox.setToolTip("ON/OFF")
        self.rocCheckBox.setToolTip("ON/OFF")
        self.cciCheckBox.setToolTip("ON/OFF")
        self.rsiCheckBox.setToolTip("ON/OFF")
        self.williamsCheckBox.setToolTip("ON/OFF")
        self.risingBreakawayGapCheckBox.setToolTip("ON/OFF")
        self.risingContinuationGapCheckBox.setToolTip("ON/OFF")
        self.fallingExhaustionGapCheckBox.setToolTip("ON/OFF")
        self.fallingBreakawayGapCheckBox.setToolTip("ON/OFF")
        self.risingExhaustionGapCheckBox.setToolTip("ON/OFF")
        self.fallingContinuationGapCheckBox.setToolTip("ON/OFF")
        self.bull3CheckBox.setToolTip("ON/OFF")
        self.morningStarCheckBox.setToolTip("ON/OFF")
        self.bear3CheckBox.setToolTip("ON/OFF")
        self.piercingCheckBox.setToolTip("ON/OFF")
        self.eveningStarCheckBox.setToolTip("ON/OFF")
        self.darkCloudCheckBox.setToolTip("ON/OFF")


    def retranslateUi(self):
        self.setWindowTitle(QtGui.QApplication.translate("self", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("self", "Positive Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setToolTip(QtGui.QApplication.translate("self", " all Reversal of rising trend:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("self", "Reversal of rising trend:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setToolTip(QtGui.QApplication.translate("self", "  Reversal of falling trend:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("self", "Reversal of falling trend:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("self", "Trend", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setToolTip(QtGui.QApplication.translate("self", "Falling Exhaustion Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("self", "Falling Exhaustion Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setToolTip(QtGui.QApplication.translate("self", "Rising Continuation Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("self", "Rising Continuation Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setToolTip(QtGui.QApplication.translate("self", "Momentum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("self", "Momentum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setToolTip(QtGui.QApplication.translate("self", "Symetric Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("self", "Symetric Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setToolTip(QtGui.QApplication.translate("self", "", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("self", "Piercing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setToolTip(QtGui.QApplication.translate("self", "Bollinger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("self", "Bollinger", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setToolTip(QtGui.QApplication.translate("self", "Bull 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("self", "Bull 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setToolTip(QtGui.QApplication.translate("self", "Rising Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("self", "Rising Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setToolTip(QtGui.QApplication.translate("self", "Williams", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("self", "Williams", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultPushButton.setText(QtGui.QApplication.translate("self", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setToolTip(QtGui.QApplication.translate("self", "Bear 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("self", "Bear 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setToolTip(QtGui.QApplication.translate("self", "Triple Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("self", "Triple Top", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setToolTip(QtGui.QApplication.translate("self", "Morning Star", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("self", "Morning Star", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setToolTip(QtGui.QApplication.translate("self", "RSI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("self", "RSI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setToolTip(QtGui.QApplication.translate("self", "New High New Low", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("self", "New High New Low", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setToolTip(QtGui.QApplication.translate("self", "CCI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("self", "CCI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setToolTip(QtGui.QApplication.translate("self", "Evening Star", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("self", "Evening Star", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setToolTip(QtGui.QApplication.translate("self", " Formations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("self", "Formations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setToolTip(QtGui.QApplication.translate("self", "Falling Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("self", "Falling Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setToolTip(QtGui.QApplication.translate("self", "Rising Exhaustion Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("self", "Rising Exhaustion Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setToolTip(QtGui.QApplication.translate("self", "Head and Shoulders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("self", "Head and Shoulders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setToolTip(QtGui.QApplication.translate("self", "Rising Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("self", "Rising Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setToolTip(QtGui.QApplication.translate("self", "Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("self", "Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setToolTip(QtGui.QApplication.translate("self", "Oscilators", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("self", "Oscilators", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setToolTip(QtGui.QApplication.translate("self", "ROC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("self", "ROC", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setToolTip(QtGui.QApplication.translate("self", "Falling Continuation Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("self", "Falling Continuation Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setToolTip(QtGui.QApplication.translate("self", "Dark Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("self", "Dark Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setToolTip(QtGui.QApplication.translate("self", "Falling Breakaway Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("self", "Falling Breakaway Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setToolTip(QtGui.QApplication.translate("self", "Rising Breakaway Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("self", "Rising Breakaway Gap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setToolTip(QtGui.QApplication.translate("self", "Triple Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("self", "Triple Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setToolTip(QtGui.QApplication.translate("self", "Falling Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("self", "Falling Wedge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setToolTip(QtGui.QApplication.translate("self", "Reversed Head and Shoulders ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("self", "Reversed Head and Shoulders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("self", "Negetive Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setToolTip(QtGui.QApplication.translate("self", " Continuation of trend", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("self", "Continuation of trend:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setToolTip(QtGui.QApplication.translate("self", " Sell signal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("self", "Sell signal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setToolTip(QtGui.QApplication.translate("self", " Buy singal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("self", "Buy singal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setToolTip(QtGui.QApplication.translate("self", " Candlestick Patterns ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("self", "Candlestick Patterns ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setToolTip(QtGui.QApplication.translate("self", " Indicators and Oscilators", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("self", "Indicators and Oscilators:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setToolTip(QtGui.QApplication.translate("self", " Gaps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("self", "Gaps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setToolTip(QtGui.QApplication.translate("self", " Rising gaps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("self", "Rising gaps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setToolTip(QtGui.QApplication.translate("self", " Falling gaps", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("self", "Flag Pennant", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("self", "Falling gaps:", None, QtGui.QApplication.UnicodeUTF8))

    def defaultValues(self):
        self.loadVal()
class ColorComboBox(QtGui.QComboBox):
    def __init__(self):
        QtGui.QComboBox.__init__(self)
        self.initModel()
    def initModel(self):           
        pixmap = QtGui.QPixmap(26, 26)
        pixmap.fill(QtGui.QColor('red'))
        icon = QtGui.QIcon(pixmap)
        self.addItem(icon,'')
        pixmap.fill(QtGui.QColor('blue'))
        icon = QtGui.QIcon(pixmap)
        self.addItem(icon,'')
        pixmap.fill(QtGui.QColor('yellow'))
        icon = QtGui.QIcon(pixmap)
        self.addItem(icon,'')
        pixmap.fill(QtGui.QColor('black'))
        icon = QtGui.QIcon(pixmap)
        self.addItem(icon,'')
        pixmap.fill(QtGui.QColor('green'))
        icon = QtGui.QIcon(pixmap)
        self.addItem(icon,'')
        pixmap.fill(QtGui.QColor('cyan'))
        icon = QtGui.QIcon(pixmap)
        self.addItem(icon,'')
        self.setToolTip("set color")
class LineStyleComboBox(QtGui.QComboBox):
    def __init__(self):
        QtGui.QComboBox.__init__(self)
        self.initModel()
    def initModel(self):           
        self.addItem(_fromUtf8(""))
        self.addItem(_fromUtf8(""))
        self.addItem(_fromUtf8(""))
        self.addItem(_fromUtf8(""))
        self.setToolTip("set line style")

        self.retranslateUi(self)
        

    def retranslateUi(self, Form):
        self.setItemText(0, QtGui.QApplication.translate("Form", "——",None,QtGui.QApplication.UnicodeUTF8))
        self.setItemText(1, QtGui.QApplication.translate("Form", "– – –", None, QtGui.QApplication.UnicodeUTF8))
        self.setItemText(2, QtGui.QApplication.translate("Form", "– • –", None, QtGui.QApplication.UnicodeUTF8))
        self.setItemText(3, QtGui.QApplication.translate("Form", "• • • ", None, QtGui.QApplication.UnicodeUTF8))

    
